// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: equipments/equipments.proto

package equipments

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionResponse3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Succes bool `protobuf:"varint,1,opt,name=succes,proto3" json:"succes,omitempty"`
}

func (x *ActionResponse3) Reset() {
	*x = ActionResponse3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipments_equipments_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionResponse3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse3) ProtoMessage() {}

func (x *ActionResponse3) ProtoReflect() protoreflect.Message {
	mi := &file_equipments_equipments_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse3.ProtoReflect.Descriptor instead.
func (*ActionResponse3) Descriptor() ([]byte, []int) {
	return file_equipments_equipments_proto_rawDescGZIP(), []int{0}
}

func (x *ActionResponse3) GetSucces() bool {
	if x != nil {
		return x.Succes
	}
	return false
}

type GetAllPagedEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *GetAllPagedEquipmentRequest) Reset() {
	*x = GetAllPagedEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipments_equipments_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllPagedEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPagedEquipmentRequest) ProtoMessage() {}

func (x *GetAllPagedEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_equipments_equipments_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPagedEquipmentRequest.ProtoReflect.Descriptor instead.
func (*GetAllPagedEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_equipments_equipments_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllPagedEquipmentRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAllPagedEquipmentRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PagedEquipmentDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*EquipmentDto3 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PagedEquipmentDto) Reset() {
	*x = PagedEquipmentDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipments_equipments_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PagedEquipmentDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PagedEquipmentDto) ProtoMessage() {}

func (x *PagedEquipmentDto) ProtoReflect() protoreflect.Message {
	mi := &file_equipments_equipments_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PagedEquipmentDto.ProtoReflect.Descriptor instead.
func (*PagedEquipmentDto) Descriptor() ([]byte, []int) {
	return file_equipments_equipments_proto_rawDescGZIP(), []int{2}
}

func (x *PagedEquipmentDto) GetItems() []*EquipmentDto3 {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetAllEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllEquipmentRequest) Reset() {
	*x = GetAllEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipments_equipments_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllEquipmentRequest) ProtoMessage() {}

func (x *GetAllEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_equipments_equipments_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllEquipmentRequest.ProtoReflect.Descriptor instead.
func (*GetAllEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_equipments_equipments_proto_rawDescGZIP(), []int{3}
}

type EquipmentListDto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*EquipmentDto3 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *EquipmentListDto) Reset() {
	*x = EquipmentListDto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipments_equipments_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentListDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentListDto) ProtoMessage() {}

func (x *EquipmentListDto) ProtoReflect() protoreflect.Message {
	mi := &file_equipments_equipments_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentListDto.ProtoReflect.Descriptor instead.
func (*EquipmentListDto) Descriptor() ([]byte, []int) {
	return file_equipments_equipments_proto_rawDescGZIP(), []int{4}
}

func (x *EquipmentListDto) GetItems() []*EquipmentDto3 {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Equipment *EquipmentDto3 `protobuf:"bytes,1,opt,name=equipment,proto3" json:"equipment,omitempty"`
}

func (x *CreateEquipmentRequest) Reset() {
	*x = CreateEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipments_equipments_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEquipmentRequest) ProtoMessage() {}

func (x *CreateEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_equipments_equipments_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEquipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_equipments_equipments_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEquipmentRequest) GetEquipment() *EquipmentDto3 {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type UpdateEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32          `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Equipment *EquipmentDto3 `protobuf:"bytes,2,opt,name=equipment,proto3" json:"equipment,omitempty"`
}

func (x *UpdateEquipmentRequest) Reset() {
	*x = UpdateEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipments_equipments_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEquipmentRequest) ProtoMessage() {}

func (x *UpdateEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_equipments_equipments_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEquipmentRequest.ProtoReflect.Descriptor instead.
func (*UpdateEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_equipments_equipments_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEquipmentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateEquipmentRequest) GetEquipment() *EquipmentDto3 {
	if x != nil {
		return x.Equipment
	}
	return nil
}

type DeleteEquipmentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteEquipmentRequest) Reset() {
	*x = DeleteEquipmentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipments_equipments_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteEquipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEquipmentRequest) ProtoMessage() {}

func (x *DeleteEquipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_equipments_equipments_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEquipmentRequest.ProtoReflect.Descriptor instead.
func (*DeleteEquipmentRequest) Descriptor() ([]byte, []int) {
	return file_equipments_equipments_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEquipmentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EquipmentDto3 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *EquipmentDto3) Reset() {
	*x = EquipmentDto3{}
	if protoimpl.UnsafeEnabled {
		mi := &file_equipments_equipments_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipmentDto3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipmentDto3) ProtoMessage() {}

func (x *EquipmentDto3) ProtoReflect() protoreflect.Message {
	mi := &file_equipments_equipments_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipmentDto3.ProtoReflect.Descriptor instead.
func (*EquipmentDto3) Descriptor() ([]byte, []int) {
	return file_equipments_equipments_proto_rawDescGZIP(), []int{8}
}

func (x *EquipmentDto3) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EquipmentDto3) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EquipmentDto3) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_equipments_equipments_proto protoreflect.FileDescriptor

var file_equipments_equipments_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a,
	0x0f, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x33,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x22, 0x4d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x64, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x39, 0x0a, 0x11, 0x50, 0x61, 0x67, 0x65, 0x64,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x74, 0x6f, 0x12, 0x24, 0x0a, 0x05,
	0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x74, 0x6f, 0x33, 0x52, 0x05, 0x69, 0x74, 0x65,
	0x6d, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x38, 0x0a, 0x10,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x74, 0x6f,
	0x12, 0x24, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x74, 0x6f, 0x33, 0x52,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x46, 0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2c, 0x0a, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44,
	0x74, 0x6f, 0x33, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x56,
	0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x09, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x74, 0x6f, 0x33, 0x52, 0x09, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x28, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x55, 0x0a, 0x0d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x74, 0x6f,
	0x33, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0xdd, 0x02, 0x0a, 0x11, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50, 0x61, 0x67, 0x65, 0x64, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1c, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x50,
	0x61, 0x67, 0x65, 0x64, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x50, 0x61, 0x67, 0x65, 0x64, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x74, 0x6f, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0f, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d,
	0x65, 0x6e, 0x74, 0x44, 0x74, 0x6f, 0x33, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x0f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e,
	0x74, 0x44, 0x74, 0x6f, 0x33, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x17, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x33, 0x22, 0x00, 0x42, 0x12, 0x5a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_equipments_equipments_proto_rawDescOnce sync.Once
	file_equipments_equipments_proto_rawDescData = file_equipments_equipments_proto_rawDesc
)

func file_equipments_equipments_proto_rawDescGZIP() []byte {
	file_equipments_equipments_proto_rawDescOnce.Do(func() {
		file_equipments_equipments_proto_rawDescData = protoimpl.X.CompressGZIP(file_equipments_equipments_proto_rawDescData)
	})
	return file_equipments_equipments_proto_rawDescData
}

var file_equipments_equipments_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_equipments_equipments_proto_goTypes = []interface{}{
	(*ActionResponse3)(nil),             // 0: ActionResponse3
	(*GetAllPagedEquipmentRequest)(nil), // 1: GetAllPagedEquipmentRequest
	(*PagedEquipmentDto)(nil),           // 2: PagedEquipmentDto
	(*GetAllEquipmentRequest)(nil),      // 3: GetAllEquipmentRequest
	(*EquipmentListDto)(nil),            // 4: EquipmentListDto
	(*CreateEquipmentRequest)(nil),      // 5: CreateEquipmentRequest
	(*UpdateEquipmentRequest)(nil),      // 6: UpdateEquipmentRequest
	(*DeleteEquipmentRequest)(nil),      // 7: DeleteEquipmentRequest
	(*EquipmentDto3)(nil),               // 8: EquipmentDto3
}
var file_equipments_equipments_proto_depIdxs = []int32{
	8, // 0: PagedEquipmentDto.items:type_name -> EquipmentDto3
	8, // 1: EquipmentListDto.items:type_name -> EquipmentDto3
	8, // 2: CreateEquipmentRequest.equipment:type_name -> EquipmentDto3
	8, // 3: UpdateEquipmentRequest.equipment:type_name -> EquipmentDto3
	1, // 4: EquipmentsService.GetAllPagedEquipments:input_type -> GetAllPagedEquipmentRequest
	3, // 5: EquipmentsService.GetAllEquipment:input_type -> GetAllEquipmentRequest
	5, // 6: EquipmentsService.CreateEquipment:input_type -> CreateEquipmentRequest
	6, // 7: EquipmentsService.UpdateEquipment:input_type -> UpdateEquipmentRequest
	7, // 8: EquipmentsService.DeleteEquipment:input_type -> DeleteEquipmentRequest
	2, // 9: EquipmentsService.GetAllPagedEquipments:output_type -> PagedEquipmentDto
	4, // 10: EquipmentsService.GetAllEquipment:output_type -> EquipmentListDto
	8, // 11: EquipmentsService.CreateEquipment:output_type -> EquipmentDto3
	8, // 12: EquipmentsService.UpdateEquipment:output_type -> EquipmentDto3
	0, // 13: EquipmentsService.DeleteEquipment:output_type -> ActionResponse3
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_equipments_equipments_proto_init() }
func file_equipments_equipments_proto_init() {
	if File_equipments_equipments_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_equipments_equipments_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionResponse3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipments_equipments_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllPagedEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipments_equipments_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PagedEquipmentDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipments_equipments_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipments_equipments_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentListDto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipments_equipments_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipments_equipments_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipments_equipments_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteEquipmentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_equipments_equipments_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipmentDto3); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_equipments_equipments_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_equipments_equipments_proto_goTypes,
		DependencyIndexes: file_equipments_equipments_proto_depIdxs,
		MessageInfos:      file_equipments_equipments_proto_msgTypes,
	}.Build()
	File_equipments_equipments_proto = out.File
	file_equipments_equipments_proto_rawDesc = nil
	file_equipments_equipments_proto_goTypes = nil
	file_equipments_equipments_proto_depIdxs = nil
}
